### ISSUE TITLE
📋 [TASK] - Create Use Case Participant Field Validator

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#662]
### Parent Feature

Expand Validators

### Task Description

As an AaC Developer, I want a use case participant field validator, so that I know I have valid references to use case participants within the use case definition. 

### Acceptance Criteria

- [ ] A new validator is created for use case participant field
- [ ] A unit test for the validator is created
    - [ ] Including a pass model and fail model for testing validator thoroughly
- [ ] The validator is added to the pipeline core validators if necessary
    - [ ] Script work for properly handling assert failures within pipeline to not cause pipeline failure but handle that model failed validation correctly
- [ ] The validator documentation is updated to cover the new validator
- [ ] Validator should check that participants are included as part of the use case participant field
