### ISSUE TITLE
📋 [TASK] - Field Name Suggestion Validator/Linter for typos

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#678]
### Parent Feature

#429

### Task Description

As an AaC Developer, I would like a validator/linter that can suggest a defined field name if the string difference is minimal (i.e. strung -> string), so that I can provide some quality-of-life IDE-type linting behavior. 

### Acceptance Criteria

- [ ] Check current field name for typos
- [ ] Make suggestion of most likely meant replacement
- [ ] Update documentation for suggestive behavior for field names
- [ ] Include unit tests for suggestive behavior for field names

### Unresolved questions

Want to have a design discussion around this first to make sure we understand the intent of the task, have thought through impacts for trying to incorporate the behavior, and how validation/linting would need to be modified to allow for this type of return (i.e. not just valid/invalid).

**Comment by lizzcondrey** [comment]
While the primarily use case of this supports LSP functionality, it could be incorporated with the `check` result to provide more info when an incorrect field is encountered.
