### ISSUE TITLE
📋 [TASK] - Group Validator Results by Category

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#709]
### Parent Feature

N/A

### Task Description

As an AaC developer, I want to expand the validator report information, so that the results are grouped by category (error, warning, info) with their counts.

### Acceptance Criteria

- [ ] Validation results are properly categorized between error, warning, and info
- [ ] Validation results are presented in groups based on category
- [ ] Counts of categorized results are included in report

**Comment by lizzcondrey** [comment]
Need to check, but seems that the result categories have been dropped on the return messages in the 0.4.0 work. It's just success or fail messages, nothing about error, warn, or info category. 

```
Dataref constraint failed for value 'alarm': 'alarm' not found in 'actor.name' values '['user', 'alarm_clock', 'timer', 'clock', 'alarms']'
  Source: /workspace/AaC/python/features/alarm_clock/usecase.yaml (68:2:1245:6)
```
