### ISSUE TITLE
📋 [TASK] - Investigate impacts of POPO in validation system

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#710]
### Parent Feature

NA

### Task Description

As an AaC developer, I want to investigate impacts of utilizing the new python object within the validation system, so that I can have a more reliable validation capability and can ensure the updated validation system can utilize the new python system appropriately.

### Acceptance Criteria

- [ ] Review current validation system for impacts of changing referenced object(s) (current unstructured dicts) for validation (constraints) to new python object.
- [ ] Include flags within the code base for impacted areas of validation (constraints) system.
- [ ] Document potential necessary changes to validation (constraint) system to assist with developing new validation (constraint) system.

**Comment by lizzcondrey** [comment]
Additional resources from @cvchaparro 

We'll be working on a task to flag all the places in the python package where we need to replace dictionary access references with so-called "Plain-old Python Objects" (POPOs). For this task, specifically related to validators but there will be others for other parts of the code base coming up, as well.

AaC has a concept called definitions which are basically the way one defines something using the AaC language. This means that when a model, a usecase, a schema, or anything else that can be used as a root key is created, we call it a definition. Currently, definitions are represented "under the hood" by Python dictionaries. Since JD is mostly accustomed to Java conventions/names/etc, he borrowed the concept of POJO, or Plain-old Java Object, for our use and came up with POPO - if you're more familiar with Python, you can think of this as a [dataclass](https://docs.python.org/3/library/dataclasses.html) or, for more complex options, an [attrs class](https://www.attrs.org/en/stable/overview.html). The purpose of a POPO for AaC is to make accessing attributes of generated definitions easier and more natural when writing code.

Take the following [outlined item](https://github.com/DevOps-MBSE/AaC/blob/5498f837ea38d66d026a1ec48639b819ffa06216/python/src/aac/plugins/validators/required_fields/_validate_required_fields.py#L37), for example.

As it stands, you will note we must call the helper function [get_top_level_fields](https://github.com/DevOps-MBSE/AaC/blob/5498f837ea38d66d026a1ec48639b819ffa06216/python/src/aac/lang/definitions/definition.py#L84-L100) (we can talk all about this later but, in short, this function returns the properties of a definition, as defined using the AaC DSL). Following the call to get_top_level_fields, which returns a Python dictionary, we have a call to get(DEFINITION_FIELD_FIELDS) which returns the fields defined for that definition.

If implemented correctly, POPOs would allow us to simplify this as follows: `schema_defined_fields_as_list = target_schema_definition.fields`

For this task, what I have in mind is for us to identify areas where we would need to make this change if POPOs were already in place and add a "flag comment" to indicate an area that needs to be updated when POPOs are available. I think we split out the work as follows:

Patrick:
- [ ] defined_references
- [ ] enum_values
- [ ] exclusive_fields
- [ ] reference_fields

Will:
- [ ] reference_targets
- [ ] required_fields
- [ ] requirement_references
- [ ] root_keys
- [ ] subcomponent_type

Cameron:
- [ ] undefined_Fields
- [ ] unique_names
- [ ] unique_requirement_ids
- [ ] unused_definitions
- [ ] usecase_actions
- [ ] usecase_participants
- [ ] validator_implementation

**Comment by crazynewidea** [comment]
POPO flag comments added in branch "popo-flag-comments-pm"
