### ISSUE TITLE
📋 [TASK] - Investigate impacts of POPO within Plugin System

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#711]
### Parent Feature

NA

### Task Description

As an AaC developer, I want to investigate impacts of utilizing the new python object within the Plugin system, so that I can have a more reliable plugin capability and can ensure the updated Plugin system can utilize the new python object appropriately.

### Acceptance Criteria

- [x] Review current Plugin system for impacts of changing referenced object(s) (current unstructured dicts) to new python object.
  - [x] active_context
  - [x] gen_plugin
  - [x] help_dump
  - [x] plugin_management
  - [x] primitive_type_check
- [x] Include flags within the code base for impacted areas of Plugin system.
- [x] Document potential necessary changes to Plugin system to assist with developing new Plugin system.
