### ISSUE TITLE
📋 [TASK] - Investigate new POPO within language context system

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#712]
### Parent Feature

NA

### Task Description

As an AaC developer, I want to investigate impacts of utilizing the new python object within the language context system, so that I can have a more reliable language context capability and can ensure the updated language context system can utilize the new python object appropriately.

### Acceptance Criteria

- [ ] Review current language context system for impacts of changing referenced object(s) (current unstructured dicts) to new python object.
- [ ] Include flags within the code base for impacted areas of language context system.
- [ ] Document potential necessary changes to language context system to assist with developing new language context system.
