### ISSUE TITLE
📋 [TASK] - Gen-Plugin Leverages Multiple Definition Sources Correctly

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#716]
### Parent Feature

#433

### Task Description

As an AaC Developer, I want Gen-Plugin to leverage multiple definition sources, so that all contributed definitions are properly exposed within the Active Context.

### Acceptance Criteria

- [ ] Confirm definition sources in the plugin model are used to generate definition boilerplate contribution points to expose those additional definitions via Active Context
- [ ] Update unit test for Gen-Plugin to ensure definitions from all definition sources are included
- [ ] Update documentation to explain multiple definition source contribution

**Comment by lizzcondrey** [comment]
Reshuffled tasking around, so this issue is no longer needed.

**Comment by lizzcondrey** [comment]
This was covered in the #714 effort, so can be closed out.
