### ISSUE TITLE
📋 [TASK] - POPO Data Object Logic Flagging in Remaining Plugins

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#724]
### Parent Feature

NA

### Task Description

As an AaC Developer, I want to put comment flags within the remaining plugin packages for transitioning to the new POPO data object, so that I have an understanding of the scope of the transition.

### Acceptance Criteria

- [ ] Remaining plugin packages is reviewed for old dictionary logic and has flagging comments to replace with POPO reference logic
  - [ ] gen_design_doc
  - [ ] gen_gherkin_behaviors
  - [ ] gen_plant_uml
  - [ ] gen_protobuf
  - [ ] print_spec
