### ISSUE TITLE
📋 [TASK] - Update Core Spec for Constraint Conversion

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#725]
### Parent Feature

NA

### Task Description

As an AaC Developer, I want to update the core spec of AaC to include constraints, so that I can support converting validators to constraints.

### Acceptance Criteria

- [ ] Core Spec includes a new constraint field on schema definition.
_Similar to current validation field._
https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/spec/spec.yaml#L291-L294
- [ ] Create a schema definition of Constraint.
_Similar to current Validation._ 
https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/spec/spec.yaml#L119-L149
- [ ] Create a schema definition of ConstraintReference.
_Similar to current ValidationReference_.
https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/spec/spec.yaml#L150-L159
- [ ] Create a schema definition of ConstraintInput.
_Similar to current ValidatorInput._
https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/spec/spec.yaml#L160-L167
- [ ] Create a schema definition of ConstraintOutput.
_Similar to current ValidatorOutput._
https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/spec/spec.yaml#L168-L175
- [ ] Update current validation schema definitions listed above to say DEPRECATED in description field. 
- [ ] Update current validation field in base schema definition to say DEPRECATED in description field.

**Comment by lizzcondrey** [comment]
Per working PR #714 and [this comment thread](https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1431768374), this task was determined to be met and be eligible for closure.
