### ISSUE TITLE
📋 [TASK] - Auto-Generate POPO

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#726]
### Parent Feature

NA

### Task Description

As an AaC developer, I want to auto-generate the POPO for AaC, so that I can convert the legacy systems.

### Acceptance Criteria

- [ ] AaC creates a POPO data object from a YAML definition.
- [ ] Create unit tests exercising the POPO creation.
- [ ] Update definition creation documentation to explain new POPO generation.

**Comment by lizzcondrey** [comment]
Per team agreement in [this comment thread](https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1449253287) on #714 , this item is eligible for closure.
