### ISSUE TITLE
📋 [TASK] - Convert Validate Package to New Constraint System

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#727]
### Parent Feature

NA

### Task Description

As an AaC developer, I want to expand the current validate package in AaC to leverage the new constraint system, so that my current validators can be converted to the constrainers.

### Acceptance Criteria

- [ ] Validate package in src/aac is modified to retrieve and leverage the new constrainers defined on definitions
  - [ ] _validate is updated.
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L112
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L131
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L143
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L163
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L167
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L233-L235
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_validate.py#L267
  - [ ] _collect_validators is updated.
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_collect_validators.py#L14
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_collect_validators.py#L63
    - https://github.com/DevOps-MBSE/AaC/blob/0b2eb2b419c06f929f072a24ac94224ea18a4119/python/src/aac/validate/_collect_validators.py#L68
  - [ ] _validation_error is updated.
- [ ] Update unit tests as necessary for the Validate Package to test the new constraint system 
  - [ ] test_validate
  - [ ] test_collect_validators

**Comment by lizzcondrey** [comment]
Per working PR #714 and [this comment thread](https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433063854), this task was determined to be eligible for closure.
