### ISSUE TITLE
📋 [TASK] - Convert `reference_fields` Validator to Constrainer

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#730]
### Parent Feature

NA

### Task Description

As an AaC constrainer developer, I want to convert the legacy validator package to a new constrainer package, so that I leverage the new constraint system.

### Acceptance Criteria

- [ ] YAML definition file is updated to work with new constraint system.
- [ ] Py logic file is updated to work with new constraint system.
- [ ] Unit test is updated to reference new constraint components and utilize the new constraint system.
- [ ] Documentation is updated for the new Constrainer.
- [ ] Replace references to the validation name with new constraint name.
