### ISSUE TITLE
📋 [TASK] - Convert `unused_definitions` Validator to Constrainer

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#741]
### Parent Feature

NA

### Task Description

As an AaC constrainer developer, I want to convert the legacy validator package to a new constrainer package, so that I leverage the new constraint system.

### Acceptance Criteria

- [ ] YAML definition file is updated to work with new constraint system.
- [ ] Py logic file is updated to work with new constraint system.
- [ ] Unit test is updated to reference new constraint components and utilize the new constraint system.
- [ ] Documentation is updated for the new Constrainer.
- [ ] Replace references to the validation name with new constraint name.

**Comment by lizzcondrey** [comment]
Based on [this](https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1432886625) PR comment thread, this issue should be closed out until necessary use cases are brought up to re-implement it.
