### ISSUE TITLE
📋 [TASK] - Convert `validator_implementation` Validator to Constrainer

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#742]
### Parent Feature

NA

### Task Description

As an AaC constrainer developer, I want to convert the legacy validator package to a new constrainer package, so that I leverage the new constraint system.

### Acceptance Criteria

- [ ] YAML definition file is updated to work with new constraint system.
- [ ] Py logic file is updated to work with new constraint system.
- [ ] Unit test is updated to reference new constraint components and utilize the new constraint system.
- [ ] Documentation is updated for the new Constrainer.
- [ ] Replace references to the validation name with new constraint name.

**Comment by lizzcondrey** [comment]
Argued as no longer necessary based on additional reworks that took place within the 0.4.0 re-baseline effort. 
That discussion thread is [here](https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433047873). Closing out this ticket.
