### ISSUE TITLE
📋 [TASK] - POPO Data Object Flagging in io Package

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#752]
### Parent Feature

NA

### Task Description

As an AaC developer, I want to investigate impacts of utilizing the new python object within the parsing system, so that I can have a more reliable parsing capability and can ensure the updated parsing system can utilize the new python object appropriately.

### Acceptance Criteria

- [x] Review current parsing system for impacts of changing referenced object(s) (current unstructured dicts) to new python object.
- [x] Include flags within the code base for impacted areas of parsing system.
- [x] Document potential necessary changes to parsing system to assist with developing new language context system.

**Comment by lizzcondrey** [comment]
Believe the heaviest changes will be within the `_yaml` and  `_parse_source` files since `_yaml` is where the initial ingest of the yaml files takes place to begin parsing into the dictionary structures to be worked with. Then the conversion into AaC's understanding of a `Definition` object takes place within `_parse_source` if I am following/understanding things correctly. So, these two pieces will have more than just a change of data object to work with which is what we have to date been flagging elsewhere, but should be where the handling for translating to the new data object takes place, I believe.
