### ISSUE TITLE
📋 [TASK] - Finish up PR comments

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#771]
### Parent Feature

#714

### Task Description

Complete review and updates for documented PR comments. 

I just needed a way to track the checklist and who progress to the team...so I'm writing this issue to that end.

### Acceptance Criteria

- [x] https://github.com/DevOps-MBSE/AaC/pull/714#pullrequestreview-1809329503
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#pullrequestreview-1812464190
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435240933
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435746351
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435747857
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1439872117
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1440007993
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1446443488
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1446444696
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1446445278
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1446447878
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1446448533
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1446454172
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1447577099
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448076912
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448091114
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448096641
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448098074
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448099167
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448154097
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448155834
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448156299
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1449106267
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1449113781
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1420799368
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1420812319
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1420843879
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1411960449
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1412066820
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1412070672
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1412091257
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1430601377
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1430682905
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1432884374
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1432886625
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1448272507
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433047873
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433158808
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433190534
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434355464
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435746351
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#issuecomment-1904298568
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1430714511
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433173646
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434426268
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434479124
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434487087
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434516351
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434518067
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434523963
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434529131
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434534678
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435247273
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435269327
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435316317
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435333841
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435351556
- [x] • https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435339922
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1439665498

Some Missing Language Error Corrections
- [x] 	https://github.com/DevOps-MBSE/AaC/pull/714/files#r1444814056
- [x] https://github.com/DevOps-MBSE/AaC/pull/714/files#r1439582125
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714/files#r1444823974
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714/files#r1444823403
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1445142981
           This still needs the message corrected to match the check happening.

Spelling, grammar, phrasing, formatting, templates
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1412559871
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1421102004
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433122505
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435746840
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435747173
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434346225
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1433168532
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434412497
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434413403
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1434523963
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435346457
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435336946
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1435365529
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1440742731
- [x]  https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1440770660
- [x] https://github.com/DevOps-MBSE/AaC/pull/714#discussion_r1440986509

**Comment by jondavid-black** [comment]
Keeping a checklist of PR comments here was super helpful!  I'd recommend this in the future if we do any more substantial changes / PRs.  It's a really good way to keep track of things given the limitations encountered with the GitHub PR UI.

**Comment by jondavid-black** [comment]
I've made a few updated per the PR comments, but my tox is failing for some reason.  I get the error: `pkg_resources.ContextualVersionConflict: (build 0.7.0 (/home/jdblack/documents/repos/AaC/python/.eggs/build-0.7.0-py3.11.egg), Requirement.parse('build>=1.0.0'), {'pip-tools'})`, but it appears my packages are all up to date.  I'll take another look tomorrow when I'm less tired.

I'm going to go ahead and push my updates just so they don't get lost in some swirl.  I'm also curious to see if GitHub Actions hits the same thing I'm seeing.  Fair warning!

**Comment by jondavid-black** [comment]
All the listed PR comments have been resolved (either via code change or response).  Now the pipeline is failing due to something happening in the offline-installer test.  It looks like the `aac.aac` file can't be found when running the `version` command as a simple smoke test.  But when I look at the aac wheel file, the `aac.aac` content appears to be present.  I should caveat that I'm looking at what's produced locally when running the secure install pipeline, not what's built on GitHub Actions.  I'm not sure what the root cause is here...nothing has changed in the `secure_install` as far as I can tell.  Will keep looking.

**Comment by jondavid-black** [comment]
I've tried a few things, but still have errors:
1. The `aac.aac` file seems to be missing:  `aac.in_out.parser._parser_error.ParserError: ('<string>', ['Provided content was not YAML.  Ensure file exists. ', '/home/runner/work/AaC/AaC/python/.tox/py310/lib/python3.10/site-packages/aac/context/../aac.aac'])`
2. The `tolmi` library seems to no longer support python version earlier than `3.11`:  `ERROR: No matching distribution found for tomli>=1.1.0; python_version < "3.11"`

The first item is a total mystery to me.  The second raises the question...should we advance our base version of python support from `3.9` to `3.11`?  I run `3.11` locally and have no issues with any of the testing failures we're seeing in the pipelines.

**Comment by jondavid-black** [comment]
I tested the GitHub Actions pipelines that removed the old versions of Python...and everything passed.  <Scratching head>

Not sure what to do next.  Do we go back and fix the old versions of python or just move on?

**Comment by lizzcondrey** [comment]
I'll bring this last couple of comments up with the team while we are together tomorrow and figure out the current direction the team would like to go.

A middle ground I think could be to currently stay with the fixes you have in place of working with solely 3.11 and could have a follow up to correct for re-establishing working with the older versions so that we don't potentially lose compatibility.

**Comment by lizzcondrey** [comment]
So, this woke me up at 0230 this morning..., I believe we're going to need to fix the dependency conflict to still allow support of 3.9 because of the ripples of not working with 3.9. Looking over other project resources they currently only support up to 3.10.5, but that is not what is currently mostly deployed. And currently no timeline for 3.11 being available. 

So, we'd be killing multiple end users environments by dropping the 3.9 support. As well as preventing them from having a functioning tool at all because they don't have access to the base Python version now required.

**Comment by lizzcondrey** [comment]
> I've tried a few things, but still have errors:
> 
> 1. The `aac.aac` file seems to be missing:  `aac.in_out.parser._parser_error.ParserError: ('<string>', ['Provided content was not YAML.  Ensure file exists. ', '/home/runner/work/AaC/AaC/python/.tox/py310/lib/python3.10/site-packages/aac/context/../aac.aac'])`


Looks like your packaging step may have gotten dorkered...the path to `aac.aac` doesn't look correct. So, it's looking for it in the incorrect spot and that's why it isn't finding it to parse I think.


> The tolmi library seems to no longer support python version earlier than 3.11: ERROR: No matching distribution found for tomli>=1.1.0; python_version < "3.11"



This is going to be a headache to try and resolve, but unfortunately, I think we are going to have to besides just jumping to 3.11 because of project resource restriction. Hopefully something can be found.

**Comment by lizzcondrey** [comment]
Pending team decision on the Python version bit, I just pulled latest and did some testing of executing basic commands, leveraging example plugin to run gen-plugin and everything is seeming stable and working. 

So, believe we are right at the cusp on finally getting to merge this in!

**Comment by lizzcondrey** [comment]
```
(venv) gitpod /workspace/AaC/python (pure-py-api) $ python --version
Python 3.9.18
```
Okay, so been testing things this morning and confirming the 3.11 updates to everything because I had seen where all the pipeline pieces got modified and thought I had seen the Gitpod config as well. But seems not, so the tool itself seems to be functioning with 3.9 still, it's something about tests are only impacted by that `tomli` package and the 3.11 need it seems.

**Comment by lizzcondrey** [comment]
Team discussed and decided based on what behavior and environment configuration we were seeing in Gitpod that we should be good to move forward with the 0.4.0 and can sort out the pipeline funkiness about the later Python version and `tomli` as follow up tasking.
