### ISSUE TITLE
📋 [TASK] - Move Legacy PUML to New Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#773]
### Parent Feature

#761 

### Task Description

As an AaC developer, I need to relocate the legacy `gen-puml` plugin to a new repository, so that it is properly separated from core baseline to work the refactor efforts.

### Acceptance Criteria

- [x] Documentation of `gen-puml` is moved to the new repository.
- [x] Plugin directory for `gen-puml` is moved to the new repository.
- [x] Unit tests for `gen-puml` is moved to the new repository.

**Comment by lizzcondrey** [comment]
[AaC PUML Main](https://github.com/DevOps-MBSE/aac-puml) has been updated to include the legacy PUML code.
