### ISSUE TITLE
📋 [TASK] - Implement Project Infrastructure in New PUML Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#774]
### Parent Feature

#761 

### Task Description

As an AaC Developer, I want my project infrastructure implemented within my new repository, so that I provide a consistent and quality plugin.

### Acceptance Criteria

- [x] Include pertinent pieces from `/.github` directory.
  - [x] Include pertinent workflows for pipelines.
  - [x] Include pertinent issue templates for requests and tracking.
    - [x] Update to reference new repository housing location. 
- [x] Include pertinent documentation requirements and configurations.
  - [x] Ensure from the `/docs` directory that the necessary documentation configurations and structure were brought over.
- [x] Include pertinent project requirements and configurations.
  - [x] Root level configuration and infrastructure pieces, i.e. `setup.py`.
- [x] Configure repository for proper permissions.
  - [x] Match configuration of core AaC Repo.

**Comment by lizzcondrey** [comment]
Updated the settings around PRs to match what I am able to set within core AaC.
