### ISSUE TITLE
📋 [TASK] - Update PUML Definition to Use New Core Structures

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#775]
### Parent Feature

#761 

### Task Description

As an AaC Developer, I want the `gen-puml` plugin definition to be updated to use the new core plugin definition structure, so that I provide an updated version of the capability.

### Acceptance Criteria

- [x] `gen-puml` YAML plugin definition is updated to use new core plugin definition structures.
- [x] Correct any misspellings, legacy copy/pasta, or misinformation in the previous Plugin Definition file. 
- [x] Finalize adding generating requirements diagram command to definition.

**Comment by lizzcondrey** [comment]
https://github.com/DevOps-MBSE/aac-puml/pull/6
