### ISSUE TITLE
📋 [TASK] - Update PUML Plugin to Use New API

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#776]
### Parent Feature

#772

### Task Description

As an AaC Developer, I want to update the `gen-puml` plugin to use the new API, so that I provide an updated version of the capability. 

### Acceptance Criteria

- [ ] Utilize the `gen-plugin` command from AaC to create all boilerplate plugin files.
- [ ] `gen-puml` init is updated to use the new API.
- [ ] `gen-puml` implementation is updated to use the new API. 
- [ ] `gen-puml` unit tests are updated to use the new API.

**Comment by lizzcondrey** [comment]
This is covered under the proper repository by https://github.com/DevOps-MBSE/aac-puml/issues/4, so closing this issue out.
