### ISSUE TITLE
📋 [TASK] - Update PUML Object Diagram Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#777]
### Parent Feature

#761 

### Task Description

As an AaC Developer, I want to update the `gen-puml` `puml-object` diagram templates, so that I have a correct and consistent diagram returned to end users.

### Acceptance Criteria

- [ ] Object diagram template is updated to use AaC `generate` helper functions as necessary.
- [ ] Object diagram template is updated to use the new definition object.
- [ ] Object diagram template is updated to meet diagram needs.

**Comment by lizzcondrey** [comment]
This is covered under the proper repository by https://github.com/DevOps-MBSE/aac-puml/issues/5, so closing this issue out.
