### ISSUE TITLE
📋 [TASK] - Move Legacy Specifications to New Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#783]
### Parent Feature

#782

### Task Description

As an AaC developer, I need to relocate the legacy `aac-spec` plugin to a new repository, so that it is properly separated from core baseline to work the refactor efforts.

**Note:** This legacy plugin is not housed in the plugin directory, but under /python/src/aac/cli/builtin_commands/specifications/

### Acceptance Criteria

- [ ] Documentation of `aac-spec` is moved to the new repository.
- [ ] Plugin directory for `aac-spec` is moved to the new repository.
- [ ] Unit tests for `aac-spec` is moved to the new repository.

**Comment by lizzcondrey** [comment]
[This branch](https://github.com/DevOps-MBSE/aac-spec/tree/aac-spec) has the initial commits of migrating over the legacy pieces.
