### ISSUE TITLE
📋 [TASK] - Implement Project Infrastructure in New Specifications Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#784]
### Parent Feature

#782

### Task Description

As an AaC Developer, I want my project infrastructure implemented within my new repository, so that I provide a consistent and quality plugin.

### Acceptance Criteria

As an AaC Developer, I want my project infrastructure implemented within the new `aac-spec` repository, so that I provide a consistent and quality plugin.

AC:

- [x] Include pertinent pieces from `/.github` directory.
  - [x] Include pertinent workflows for pipelines.
  - [x] Include pertinent issue templates for requests and tracking.
    - [x] Update to reference new repository housing location. 
- [x] Include pertinent documentation requirements and configurations.
  - [x] Ensure from the `/docs` directory that the necessary documentation configurations and structure were brought over.
- [x] Include pertinent project requirements and configurations.
  - [x] Root level configuration and infrastructure pieces, i.e. `setup.py`.
- [x] Configure repository for proper permissions.
  - [x] Match configuration of core AaC Repo.

**Comment by bunchw** [comment]
I do not have access to the settings tab for the repo on github, so I am unable to complete the _Configure repository for proper permissions_ portion of the this task.

**Comment by lizzcondrey** [comment]
Updated the settings around PRs to match what I am able to set within core AaC.
