### ISSUE TITLE
📋 [TASK] - Update Specifications Plugin to Use New API

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#786]
### Parent Feature

#782

### Task Description

As an AaC Developer, I want to update the `aac-spec` plugin to use the new API, so that I provide an updated version of the capability. 

### Acceptance Criteria

- [ ] Utilize the `gen-plugin` command from AaC to create all boilerplate plugin files.
- [ ] `aac-spec` init is updated to use the new API.
- [ ] `aac-spec` implementation is updated to use the new API. 
- [ ] `aac-spec` unit tests are updated to use the new API.
