### ISSUE TITLE
📋 [TASK] - Extract `load_definitions` Method to a Separate Class

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#791]
### Parent Feature

#790

### Task Description

As an AaC Developer, I want to extract the `load_definitions()` method in `LanguageContext` to a separate class, so that I can begin to reduce the complexity of the method. 

### Acceptance Criteria

- [ ] Extract `load_definitions()` method to a new class
- [ ] Update imports to `LanguageContext` to handle extraction.
- [ ] Update `LanguageContext` logic as necessary to handle extraction.
- [ ] Update `LanguageContext` unit tests as necessary to handle extraction.
