### ISSUE TITLE
📋 [TASK] - Reduce Complexity of New Parsing Class

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#792]
### Parent Feature

#790

### Task Description

As an AaC Developer, I want to reduce the complexity of the new parsing class, so that I have a more readable and maintainable parsing capability. 

### Acceptance Criteria

- [ ] Larger methods are broken into appropriate smaller methods.
- [ ] Internal calls to methods are updated accordingly.
- [ ] Imports in LanguageContext are updated accordingly.
- [ ] External calls to methods are updated accordingly.

**Comment by lizzcondrey** [comment]
Closed with the merge in of #817
