### ISSUE TITLE
📋 [TASK] - Investigate Markdown Parsing Libraries

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#793]
### Parent Feature

#790

### Task Description

As an AaC Developer, I would like to investigate potential Markdown parsing libraries, so that I can determine the plausibility of expanding AaC parsing. 

Spend no more than two days researching potential Markdown parsing libraries that could be incorporated to AaC to provide an additional parsing capability. 

### Acceptance Criteria

- [ ] Identify potential libraries to use.
- [ ] Evaluate necessary lift for incorporating.
  - [ ] Are they already utilized packages elsewhere on project.

**Comment by lizzcondrey** [comment]
No longer necessary. Closing out.
