### ISSUE TITLE
📋 [TASK] - Determine A Potential Markdown Input Design

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#794]
### Parent Feature

#790

### Task Description

As an AaC Developer, I would like to draft a potential design of a system for supporting Markdown as an input to AaC, so that we can expand the supported model input options for end users. 

Spend no more than two days generating a draft design of supporting Markdown as an input language for the AaC tool. 

### Acceptance Criteria

- [ ] Generate a system design, i.e. UML diagram
- [ ] Evaluate lift for implementing
  - [ ] Loose timeline
  - [ ] Loose effort estimates
  - [ ] Loose tasking break out

**Comment by lizzcondrey** [comment]
No longer necessary. Closing issue.
