### ISSUE TITLE
📋 [TASK] - Investigate Re-implementing the Req-ID to Feature Files

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#795]
### Parent Feature

#790

### Task Description

As an AaC Developer, I want to investigate how to extract the requirement id from the parsed model data, so that I can re-implement it being provided within the generated feature files.

Spend no more than two days investigating extracting the requirement id from the parsed model object and being able to include it within the Jinja2 feature file template. Legacy example can be found within the gen_gherkin_behavior plugin in the PreAPI Repository. 

Result of this spike should be a path forward for completing implementation of reincorporating the requirement id to the feature files. 

### Acceptance Criteria

- [ ] Document path forward for re-implementing.
- [ ] Evaluate lift for implementing.
  - [ ] Loose timeline.
  - [ ] Loose effort estimates.
  - [ ] Loose tasking break out.

**Comment by lizzcondrey** [comment]
This may be a lighter lift, should be leveraging the Gen-Gherkin feature file template for accomplishing this, not the general feature file as part of generate because of additional info being needed in the gen-gherkin version

**Comment by bunchw** [comment]
[Investigation-documentation.txt](https://github.com/DevOps-MBSE/AaC/files/15195160/Investigation-documentation.txt)

**Comment by bunchw** [comment]
[Investigation-documentation.txt](https://github.com/DevOps-MBSE/AaC/files/15202105/Investigation-documentation.txt)

**Comment by bunchw** [comment]
[Investigation-documentation.txt](https://github.com/DevOps-MBSE/AaC/files/15202567/Investigation-documentation.txt)

**Comment by bunchw** [comment]
[Investigation-documentation.txt](https://github.com/DevOps-MBSE/AaC/files/15202567/Investigation-documentation.txt)

**Comment by bunchw** [comment]
[Investigation-documentation.txt](https://github.com/DevOps-MBSE/AaC/files/15204360/Investigation-documentation.txt)

**Comment by lizzcondrey** [comment]
Have reviewed the txt file and have gone back and forth on the refinement of the file. Believe it is in a decent state to mark this task as complete.
