### ISSUE TITLE
📋 [TASK] - Update Plugin Unit Test Generation Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#804]
### Parent Feature

#801

### Task Description

As an AaC Developer, I want to update the content of the plugin implementation template, so that it is better organized and references appropriate model definition components. 

 

AC:

### Acceptance Criteria

- [ ] Clean up imports
  - [ ] Alphabetize
  - [ ] Spacing
  - [ ] Grouping
  - [ ] Duplication
- [ ] Method population
  - [ ] run before, command, run after
- [ ] Clarify editable status.
