### ISSUE TITLE
📋 [TASK] - Investigate upload-artifacts Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#807]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the upload-artifacts action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [x] Spend no more than two days researching the migration impacts of changing from v3 to v4 for upload-artifacts action in pipelines
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
[Upload & Download @v4 action breakage](https://github.com/actions/upload-artifact/issues/472)
[upload-artifact/docs/MIGRATION.md at main · actions/upload-artifact (github.com)](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)
[upload-artifact/README.md at main · actions/upload-artifact (github.com)](https://github.com/actions/upload-artifact/blob/main/README.md)
