### ISSUE TITLE
📋 [TASK] - Investigate download-artifacts Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#808]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the download-artifacts action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [x] Spend no more than two days researching the migration impacts of changing from v3 to v4 for download-artifacts action in pipelines.
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
[Upload & Download @v4 action breakage](https://github.com/actions/upload-artifact/issues/472)
[download-artifact/docs/MIGRATION.md at main · actions/download-artifact (github.com)](https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md)
[download-artifact/README.md at main · actions/download-artifact (github.com)](https://github.com/actions/download-artifact/blob/main/README.md)

We are migrating from v3 to v4, so we are able to hold on the migration till next iteration like originally thought. It's v2 that is deprecated and stopping support June 30th. November 30th is when v3 will be deprecated, which is just after the end of the next iteration. So, we are good to continue with the plan of handling all action migrations next iteration.
