### ISSUE TITLE
📋 [TASK] - Investigate setup-python Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#809]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the setup-python action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [x] Spend no more than two days researching the migration impacts of changing from v4 to v5 for setup-python action in pipelines.
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
[actions/setup-python: Set up your GitHub Actions workflow with a specific version of Python](https://github.com/actions/setup-python)

[Setup Python · Actions · GitHub Marketplace](https://github.com/marketplace/actions/setup-python)
[setup-python/docs/advanced-usage.md at main · actions/setup-python (github.com)](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md)

Here are the resources I found for setup-python action. Thankfully, this one should be a straight forward of just bump the action version since we don't do any special runners or additional handling past basic Python installs. This action did not seem to have a hard deprecation date.
