### ISSUE TITLE
📋 [TASK] - Investigate checkout Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#810]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the checkout action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [x] Spend no more than two days researching the migration impacts of changing from v3 to v4 for checkout action in pipelines.
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.
