### ISSUE TITLE
📋 [TASK] - Investigate deploy-pages Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#811]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the deploy-pages action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [x] Spend no more than two days researching the migration impacts of changing from v2 to v4 for checkout-repo action in pipelines.
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
Thankfully similar to configure-pages, seems like this should just be a simple version bump of the action. Not seeing anything new in the configuration options that we don't currently have. 

https://github.com/actions/deploy-pages/blob/main/README.md
