### ISSUE TITLE
📋 [TASK] - Investigate upload-pages-artifacts Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#812]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the upload-pages-artifact action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [x] Spend no more than two days researching the migration impacts of changing from v2 to v3 for upload-pages-artifact action in pipelines.
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
[upload-pages-artifact/action.yml at main · actions/upload-pages-artifact (github.com)](https://github.com/actions/upload-pages-artifact/blob/main/action.yml)
[upload-pages-artifact/README.md at main · actions/upload-pages-artifact (github.com)](https://github.com/actions/upload-pages-artifact/blob/main/README.md)
[Migrate to GitHub Actions from Pages Legacy Worker - JosephGuadagno.net](https://www.josephguadagno.net/2024/04/03/migrate-to-github-actions-from-pages-legacy-worker)

Another simple version bump should allow things to go smoothly. Also, in confirming the migration for this action, found the last link that outlines the approach for utilizing GitHub actions for deploying your pages, which is soon to be the primary way of doing so since the old runner is being deprecated this month it seems.
