### ISSUE TITLE
📋 [TASK] - Investigate Changes to Build Chain Impacts

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#813]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the impacts of changing the AaC build chain, so that I do not cause pipeline breakage or negatively impact downstream users. 

### Acceptance Criteria

- [x] Spend no more than two days researching the differences between setup.py vs pyproject.toml.
  - [x] Understand differences for local build.
  - [x] Understand differences for pipeline build.
  - [x] Understand differences for local testing.
  - [x] Understand differences for pipeline testing.
  - [x] Understand impacts to generate capability and changes for templates.
- [x] Identify useful resources for generating a solution for the migration.
- [x] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
@bunchw please attach the word doc of this task then can close it out on this side.

**Comment by bunchw** [comment]
[Build Chain Migration From Setup.py to pyproject.toml.txt](https://github.com/user-attachments/files/16614822/Build.Chain.Migration.From.Setup.py.to.pyproject.toml.txt)
