### ISSUE TITLE
📋 [TASK] - Investigate codeql-action Bundle Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#815]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the codeql-action bundle, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [ ] Spend no more than two days researching the migration impacts of changing from v2 to v3 for codeql-action bundle in pipelines
  - [ ] analyze
  - [ ] autobuild
  - [ ] init
- [ ] Identify useful resources for generating a solution for the migration.
- [ ] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
**Codeql-action Bundle**
- Init
- Autobuild
- Analyze

 

[codeql-action/CHANGELOG.md at main · github/codeql-action](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)

[codeql-action/README.md at main · github/codeql-action](https://github.com/github/codeql-action/blob/main/README.md)

 
The following versions of the CodeQL Action are currently supported:

v3 (latest)
v2 (deprecated, support will end on December 5th, 2024)
The only difference between CodeQL Action v2 and v3 is the version of Node.js on which they run. CodeQL Action v3 runs on Node 20, while CodeQL Action v2 runs on Node 16.

 

Thankfully based on the information in the changelog and their README, it should just be a version bump since they maintained mirrored functionality between v2 and v3 to date.
