### ISSUE TITLE
📋 [TASK] - Investigate configure-pages Version Migration

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#816]
### Parent Feature

#799

### Task Description

As an AaC CI/CD Developer, I need to investigate the version migration of the configure-pages action, so that I do not cause pipeline breakage by migrating major versions. 

### Acceptance Criteria

- [ ] Spend no more than two days researching the migration impacts of changing from v3 to v5 for configure-pages action in pipelines
- [ ] Identify useful resources for generating a solution for the migration.
- [ ] Document the potential solution(s) for implementing the migration.

**Comment by lizzcondrey** [comment]
There is nothing of note in the action's repo or documentation to point to it being more than just a bump in version for the action. And based on the commit responsible for moving to v5 and adding node20 only changed the node, no other logic. 

https://github.com/actions/configure-pages/blob/main/README.md
https://github.com/actions/configure-pages/commit/3a014131e99a7bf2daf896787a8f92789126d038
