### ISSUE TITLE
📋 [TASK] - Improvement of LanguageError Lexeme Usage

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#819]
### Parent Feature

#914 

### Task Description

As an AaC Developer, I want to implement the identified improvements for the LanguageError usage of the Lexemes, so that I provide a reliable and useful tool for end users.

### Acceptance Criteria

- [ ] LanguageError Lexeme usage is modified as necessary to better support utilization. 
  - [ ] get_location_str method is modified to return SourceLocation
  - [ ] DefinitionParser class is updated to use modified get_location method
  - [ ] Accurate location data from an erroneous parsing is provided to ExecutionMessage
- [ ] Unit tests for the Lexemes provided to LanguageError are updated.
- [ ] Documentation about utilizing Lexemes is expanded to cover the LangaugeError Lexeme usage layer.

**Comment by lizzcondrey** [comment]
While working on reducing the complexity of the parsing capability, some source location returns for raised errors were found to not meet the needs for the ExecutionMessage handling at the higher level. This was found while evaluating the improvements in the new DefinitionParser class in #817. It is beyond the scope of that task and can be addressed with an upcoming effort of re-evaluating and improving our Lexeme/location provision within AaC.
