### ISSUE TITLE
📋 [TASK] - Update AaC Core Generation Templates

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#839]
### Parent Feature

#838

### Task Description

As a AaC Developer, I want to update the generation templates in the core AaC repository, so that I utilize the new build process.

### Acceptance Criteria

- [x] Replace the setup.py generation template with a pyproject.toml template.
- [x] Edit other template files to coincide with the new build chain.
  - [x] tox.ini
  - [x] README
- [x] Implement new template files.
  - [x] MANIFEST.in template
