### ISSUE TITLE
📋 [TASK] - Migrate Build Chain in Core AaC Repo

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#840]
### Parent Feature

#838

### Task Description

As an AaC Developer, I want to update the core AaC repository to use the new build chain process, so that I have a consistent build chain across project repositories.

### Acceptance Criteria

- [ ] Replace setup.py file with a pyproject.toml file in core AaC repo.
- [ ] Edit other build and infrastructure files as needed.
  - [ ] Manifest.in
  - [ ] tox.ini
  - [ ] README
- [ ] Pull latest build workflows from organization templates as needed
