### ISSUE TITLE
📋 [TASK] - Update Workflows in AaC Core Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#843]
### Parent Feature

#842

### Task Description

As an AaC Developer, I want to pull the latest workflows for the Core AaC Repository, so that I have the latest supported pipelines.

### Acceptance Criteria

- [x] Pull the updated python-build-and-lint.yml workflow
- [x] Pull the updated python-cross-platform-support.yml workflow
- [x] Pull the updated python-deploy-artifacts.yml workflow
- [x] Pull the updated python-test-python-version.yml workflow
- [x] Pull the updated codeql-analysis.yml workflow
- [x] Pull the updated deploy-pages.yml workflow
- [x] Pull the updated main-branch.yml workflow
- [x] Pull the updated pull-requests.yml workflow
- [x] Pull the updated dependabot.yml configuration.
- [x] Remove legacy issue templates
- [x] Remove legacy PR template
