### ISSUE TITLE
📋 [TASK] - Improve Tests in Check Unit Tests

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#846]
### Parent Feature

#844

### Task Description

As an AaC Test Developer, I want to expand the test coverage in my unit tests, so that I can have more confidence in the robustness of my code.

### Acceptance Criteria

- [ ] Update test logic as necessary to expand test coverage. 
  - [ ] Happy path and sad path at a minimum
- [ ] (Stretch) Incorporate a behave feature file for testing if applicable.
