### ISSUE TITLE
📋 [TASK] - Improve Tests in In/Out Unit Tests

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#848]
### Parent Feature

#844

### Task Description

As an AaC Test Developer, I want to remove nose2 usage from my unit tests, so that I can more easily use pytest and VSCode for debugging unit tests.

### Acceptance Criteria

- [x] Remove nose2 package from unit tests.
- [x] Replace with equivalent pytest package.
- [x] Update test logic as necessary to expand test coverage. 
  - [x] Happy path and sad path at a minimum
- [ ] (Stretch) Incorporate a behave feature file for testing if applicable.

**Comment by jasoncbryant** [comment]
Replaced nose2 with parameterized test sets for both success and fail cases.
Some unexpected results documented in https://github.com/DevOps-MBSE/AaC/issues/880
