### ISSUE TITLE
📋 [TASK] - Improve Tests in Exclusive Fields Unit Tests

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#852]
### Parent Feature

#844

### Task Description

As an AaC Test Developer, I want to expand the test coverage in my unit tests, so that I can have more confidence in the robustness of my code.

### Acceptance Criteria

- [x] Update test logic as necessary to expand test coverage. 
  - [x] Happy path and sad path at a minimum
- [x] (Stretch) Incorporate a behave feature file for testing if applicable.
- [x] Run `flake8` on the targeted test directory and address findings.
- [ ] Document any identified gaps.
