### ISSUE TITLE
📋 [TASK] - Improve Tests in Root Schema Must Have Name Unit Tests

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#857]
### Parent Feature

#844

### Task Description

As an AaC Test Developer, I want to expand the test coverage in my unit tests, so that I can have more confidence in the robustness of my code.

### Acceptance Criteria

- [ ] Update test logic as necessary to expand test coverage. 
  - [ ] Happy path and sad path at a minimum
- [ ] (Stretch) Incorporate a behave feature file for testing if applicable.
- [ ] Run `flake8` on the targeted test directory and address findings.
- [ ] Document any identified gaps.
