### ISSUE TITLE
📋 [TASK] - Investigate Dot Notation Navigation

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#895]
### Parent Feature

NA

### Task Description

As an AaC Developer, I want to investigate the inconsistency of leveraging the dot notation for navigating the definition structures, so that I have a better understanding of the data structures leveraged within AaC core and its plugins.

### Acceptance Criteria

Spend no more than three days investigating the dot notation navigation of definition structures behavior.

- [ ] Document any found inconsistencies/nuances for usage
- [ ] Determine if corrections need made to the definition class and data structure implementation
  - [ ] If no corrections needed, determine necessary documentation improvements to make clearer how to properly utilize the data structure

**Comment by lizzcondrey** [comment]
EXAMPLE


definition.acceptance.behavior.given rather than something like definition.structure["acceptance"]["behavior"]["given"]

We have places within the code base that we can utilize the dot notation to navigate the definition structure and there are other places that we seem to be unable to and have had to utilize the dictionary key navigation instead. These two approaches are most commonly found within any logic related to our generate type commands within PUML and Gherkin.
