### ISSUE TITLE
📋 [TASK] - Pip Upgrade Steps

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#896]
### Parent Feature

N/A

### Task Description

As an AaC Developer, I need to update my gitpod.yml file to include a `pip install --upgrade pip` step, so that my dev environment is up to date.

### Acceptance Criteria

- [ ] Confirm all repositories have:
  - [ ] gitpod.yml file has a step before package install for upgrading pip.
  - [ ] gitpod.yml file package install step is consistently set for .[all] so that all dependencies are properly installed
