### ISSUE TITLE
📋 [TASK] - Output Paths for Code Generation Corrected

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#897]
### Parent Feature

N/A

### Task Description

As an AaC Developer, I would like my generated outputs to assign to the appropriate level of directory, so that my boilerplate codebase structure best adheres to expectation and documentation. 

### Acceptance Criteria

- [ ] Plugin code output goes appropriately to python/src/*
  - [ ] With the inclusion of the appended package path from definition
- [ ] Unit tests output goes appropriately to python/test/*
- [ ] Documentation output goes appropriately to docs/*
- [ ] Project code output goes appropriately to python/*
