### ISSUE TITLE
📋 [TASK] - Plugin Feature Jinja2 Template Mapping

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#898]
### Parent Feature

N/A

### Task Description

As an AaC Developer, I would like to correct the template mapping, so that I reference the appropriate model component at the appropriate time. 

### Acceptance Criteria

- [ ] "When" steps in the template map to "When" entries from the model.
- [ ] "Then" steps in the template map to "Then" entries from the model.
- [ ] Unit test is updated to confirm appropriate steps are populating.
