### ISSUE TITLE
📋 [TASK] -  get_definitions_by_name() Handling Names with Spaces

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#900]
### Parent Feature

N/A

### Task Description

As an AaC developer, I want to investigate, determine, and implement a fix for the inconsistency of get_definitions_by_name() finding definitions with spaces in the name.

### Acceptance Criteria

- [ ] The reason for the inconsistency is determined.
- [ ] A fix is implemented, If applicable.
- [ ] Documentation is updated to provide clearer guidance on naming.
