### ISSUE TITLE
📋 [TASK] - Investigate Container Hardening Needs

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#910]
### Parent Feature

#909

### Task Description

As an AaC CI/CD Developer, I want to determine container hardening requirements, so that I can deliver a properly configured container.

### Acceptance Criteria

- [ ] Spend no more than two days investigating what potential hardening may be needed of the container image.
- [ ] Determine any applicable/required STIGs
- [ ] Determine implementation of applying identified STIGs
- [ ] Determine evaluation process of confirming STIG application

**Comment by lizzcondrey** [comment]
Write up was generated and included with project reference materials.
