### ISSUE TITLE
📋 [TASK] - Standardize Docker Files

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#911]
### Parent Feature

#909

### Task Description

As an AaC CI/CD Developer, I want to determine the proper standardization for the repository Docker files, so that I can provide a consistent and reliable container for development efforts.

### Acceptance Criteria

- [ ] Investigate differences between repository Docker files
- [ ] Make necessary configuration changes for a central Docker file
- [ ] Confirm Gitpod from any repository can use the central configuration

**Comment by lizzcondrey** [comment]
No changes were necessary for this repository. It was the root example.
