### ISSUE TITLE
📋 [TASK] - Improvement to Lexeme Class

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#916]
### Parent Feature

#914 

### Task Description

As an AaC Developer, I want to implement the identified improvements for the Lexeme Class, so that I provide a reliable and useful tool for end users.

### Acceptance Criteria

- [ ] Lexeme class is modified as necessary to better support utilization.
- [ ] Unit tests for the Lexeme class are updated.
- [ ] Documentation about utilizing Lexemes is added to the Developer's Guide.

**Comment by bunchw** [comment]
The changes that are needed are not in the Lexeme class itself.  The lexeme class does not really have much in it, so the things that need to change are in its implementation and use by Language Error and parsing.
