### ISSUE TITLE
📋 [TASK] - Improvement to Cache Layer of Lexeme

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#917]
### Parent Feature

#914

### Task Description

As an AaC Developer, I want to implement the identified improvements for the cache layer of the Lexemes, so that I provide a reliable and useful tool for end users.

### Acceptance Criteria

- [ ] Lexeme cache layer is modified as necessary to better support utilization.
- [ ] Unit tests for the Lexeme cache are updated.
- [ ] Documentation about utilizing Lexemes is expanded to cover the Lexeme cache.

**Comment by bunchw** [comment]
The cache class, which is where the yaml string parsing happens, does not require changes.  The real changes needed with the lexemes are in how they are utilized elsewhere.
