### ISSUE TITLE
📋 [TASK] - Improvement to Definition Parser Layer

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#919]
### Parent Feature

#914

### Task Description

As an AaC Developer, I want to implement the identified improvements for the definition parser layer of the Lexemes, so that I provide a reliable and useful tool for end users.

### Acceptance Criteria

- [ ] Lexeme parse layer is modified as necessary to better support utilization.
- [ ] Unit tests for the Lexeme parse are updated.
- [ ] Documentation about utilizing Lexemes is expanded to cover the Lexeme parse layer.
