### ISSUE TITLE
📋 [TASK] - Improvement of ExecutionMessage Class

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#920]
### Parent Feature

#914

### Task Description

As an AaC Developer, I want to implement the identified improvements for the ExecutionMessage Class usage of the Lexemes, so that I provide a reliable and useful tool for end users.

### Acceptance Criteria

- [ ] ExecutionMessage Class usage of Lexemes is modified as necessary to better support utilization.
- [ ] Unit tests for the ExecutionMessage Class are updated.
- [ ] Documentation about utilizing Lexemes is expanded to cover the ExecutionMessage Class usage of Lexemes.

### Helpful information
https://github.com/DevOps-MBSE/AaC/pull/934#discussion_r1884263966
