### ISSUE TITLE
📋 [TASK] - Plugin Documentation Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/AaC#929]
### Parent Feature

#928

### Task Description

As an AaC Documenter, I want to create and implement a plugin documentation template, so that I can provide consistent documentation when a new plugin is made.

### Acceptance Criteria

- [ ] Include all pertinent sections of the plugin documentation page like what exists now in manually generated pages.
- [ ] Include reminders for injection of pertinent screen shots.
- [ ] Include reminders for injection of example usage.
- [ ] Include reminders for injection of example output.
- [ ] Include as part of output of gen-plugin command.
